# Generated by Django 2.1.2 on 2018-12-20 12:02

from django.db import migrations
import visits.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181209_1511'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInOlimp',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('accounts.useraccount',),
            managers=[
                ('objects', visits.models.UserInOlimpManager()),
            ],
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='entrance_to_olimp',
            new_name='enter_timestamp',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='last_visit',
            new_name='leave_timestamp',
        ),
    ]
