# Generated by Django 2.1.2 on 2019-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20181220_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'посещение', 'verbose_name_plural': 'посещения'},
        ),
        migrations.AlterField(
            model_name='visit',
            name='enter_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время входа'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='leave_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время вЫхода'),
        ),
    ]
