# Generated by Django 2.1.2 on 2020-03-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20191112_2022'),
        ('visits', '0003_auto_20191105_1931'),
    ]

    operations = [
    ]
