# Generated by Django 2.1.2 on 2020-03-19 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macmodeluser',
            options={'verbose_name': 'Mac-адрес', 'verbose_name_plural': 'Mac-адреса'},
        ),
        migrations.AlterField(
            model_name='macmodeluser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mac_address', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
