# Generated by Django 2.1.2 on 2019-11-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macmodeluser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mac_address', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]

# DELETE FROM accounts_useraccount WHERE id='';