# Generated by Django 2.1.2 on 2018-12-01 22:22

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', accounts.models.AccountManager()),
            ],
        ),
    ]
