# Generated by Django 2.1.2 on 2018-12-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinolimp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='in_olimp',
            field=models.BooleanField(default=False),
        ),
    ]
