# Generated by Django 2.1.2 on 2018-12-04 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_in_olimp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinolimp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
