# Generated by Django 2.1.2 on 2018-12-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181209_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='in_olimp',
        ),
    ]
