# Generated by Django 2.1.2 on 2019-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_useraccount_in_olimp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identify_data',
            field=models.CharField(blank=True, max_length=11, verbose_name='Паспортные данные'),
        ),
    ]
