# Generated by Django 2.1.2 on 2019-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_identify_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата посещения', verbose_name='дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата печати')),
                ('guests', models.ManyToManyField(to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'служебная записка',
                'verbose_name_plural': 'служебные записки',
            },
        ),
    ]
