# Generated by Django 2.1.2 on 2019-12-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_servicedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedocument',
            name='doc_type',
            field=models.CharField(choices=[('temp', 'на временный пропуск'), ('single', 'на разовый пропуск'), ('over_time', 'на проход вечером')], default='over_time', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='guests',
            field=models.ManyToManyField(to='accounts.Profile', verbose_name='гости'),
        ),
    ]
