# Generated by Django 2.1.2 on 2020-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191203_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото пользователя'),
        ),
    ]
