# Generated by Django 2.1.2 on 2020-03-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191203_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lab_position',
            field=models.CharField(choices=[('boss', 'Руководитель'), ('master', 'Мастер'), ('member', 'Участник'), ('guest', 'Гость')], default='guest', max_length=30),
        ),
    ]
