# Generated by Django 2.1.2 on 2020-03-20 11:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оценка')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100, verbose_name='Университет')),
                ('subdivision', models.CharField(help_text='Подразделение, факультет', max_length=100, verbose_name='Подразделение')),
                ('department', models.CharField(help_text='кафедра', max_length=100, verbose_name='Кафедра')),
                ('begin_year', models.SmallIntegerField(help_text='Начало обучения', verbose_name='Год начала обучения')),
                ('end_year', models.SmallIntegerField(help_text='Окончание обучения', verbose_name='Год окончания обучения')),
                ('group', models.CharField(help_text='Группа', max_length=10, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'высшее образование',
                'verbose_name_plural': 'высшие образования',
            },
        ),
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('rate_methods', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оценка методики')),
            ],
            options={
                'verbose_name': 'Методика',
                'verbose_name_plural': 'Методики',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Путь к фотографии')),
                ('is_visible', models.CharField(choices=[('1', 'Видимый'), ('2', 'Скрытый')], default='1', max_length=1, verbose_name='Тип проектв')),
                ('status_project', models.CharField(choices=[('1', 'Текущий'), ('2', 'Завершенный'), ('3', 'Запланнированный')], default='1', max_length=1, verbose_name='Статус проекта')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Profile')),
                ('interests', models.TextField(blank=True, null=True, verbose_name='Интересы пользователя')),
                ('grade', models.SmallIntegerField(help_text='Уровнь владения навыком')),
                ('private', models.CharField(choices=[('0', 'Видно только мне'), ('1', 'Видно всем'), ('2', 'Видно друзьям'), ('3', 'Видно колегам')], default='0', max_length=1, verbose_name='приватность')),
            ],
            options={
                'verbose_name': 'Навык пользователя',
                'verbose_name_plural': 'Навыки пользователей',
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название навыка')),
                ('approved', models.BooleanField(default=False, verbose_name='Подтверждение навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='TypeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название типа связи')),
            ],
            options={
                'verbose_name': 'Тип связи',
                'verbose_name_plural': 'Типы связей',
            },
        ),
        migrations.CreateModel(
            name='TypeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название типа навыка')),
            ],
            options={
                'verbose_name': 'Тип навыка',
                'verbose_name_plural': 'Типы навыка',
            },
        ),
        migrations.AddField(
            model_name='skills',
            name='type_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.TypeSkill', verbose_name='Тип навыка'),
        ),
        migrations.AddField(
            model_name='skillprofile',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='area_user', to='portfolio.Skills', verbose_name='Проффессиональная сфера'),
        ),
        migrations.AddField(
            model_name='skillprofile',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Education', verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='skillprofile',
            name='skills_user',
            field=models.ManyToManyField(blank=True, related_name='skill_user', to='portfolio.Skills', verbose_name='Навыки пользоателя'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='from_skill',
            field=models.ManyToManyField(related_name='from_skill', to='portfolio.Skills'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='to_skill',
            field=models.ManyToManyField(related_name='to_skill', to='portfolio.Skills'),
        ),
        migrations.AddField(
            model_name='relationships',
            name='type_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.TypeRelationship', verbose_name='Тип связи'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Skills', verbose_name='Навыки'),
        ),
    ]
